DATABASE:
  HOST: "localhost"
  PORT: 5432
  DB_NAME: "goat"
  USER: "goat"
  PASSWORD: "earlmanigault"

DATA_SOURCE:  
  #"no_download" if you don't want to download OSM data automatically. Make sure that the file is called raw-osm.osm.pbf.
  OSM_DOWNLOAD_LINK: "https://download.geofabrik.de/europe/germany/bayern/oberbayern-latest.osm.pbf" 
  #"most_recent" if the data from the OSM-Download-Link has not the recency you need. 
  OSM_DATA_RECENCY: "standard"
  BUFFER_BOUNDING_BOX: 0.045 #in degree (default: approx. 3km)
  EXTRACT_BBOX: "yes"
  

DATA_REFINEMENT_VARIABLES:
  #extrapolation ==> census.shp + landuse.shp needed as input
  #disaggregation ==> landuse.shp needed as input + high-resolution population input data + building data
  #distribution ==> landuse.sho need as input + high-resolution population input data 
  #custom_population ==> population.shp custom population data needed  
  POPULATION: "extrapolation"
  #"yes" if you want to add these layers 
  ADDITIONAL_WALKABILITY_LAYERS: "no" 
  variable_container:
    heatmap_auto_refresh: "'yes'"
    pois_one_entrance: ["kindergarten","nursery","primary_school","secondary_school","bar","biergarten","cafe","pub","fast_food","ice_cream","restaurant","theatre","sum_population","cinema","library","night_club","recycling",
      "car_sharing","bicycle_rental","charging_station","bus_station","tram_station","subway_station","railway_station","taxi","hairdresser","atm","bank","dentist","doctors","pharmacy","post_box","post_office","fuel",
      "bakery","butcher","clothes","convenience","general","fashion","florist","greengrocer","kiosk","mall","shoes","sports","supermarket","health_food","discount_supermarket",
      "hypermarket","international_supermarket","chemist","organic","marketplace",
      "hotel","museum","hostel","guest_house","viewpoint","gallery"
    ]
    pois_more_entrances: ["bus_stop","tram_stop","subway_entrance","rail_station"]
    excluded_class_id_walking: [0,101,102,103,104,105,106,107,501,502,503,504,701,801]
    categories_no_foot: ["use_sidepath","no"]
    excluded_class_id_cycling: [0,101,102,103,104,105,106,107,501,502,503,504,701,801]
    categories_no_bicycle: ["use_sidepath","no"]
    categories_sidewalk_no_foot: ["separate"] #Used for visualization purpose only
    max_length_links: '300'
    custom_landuse_no_residents: ["AX_TagebauGrubeSteinbruch",
      "AX_SportFreizeitUndErholungsflaeche",
      "AX_FlaecheBesondererFunktionalerPraegung",
      "AX_Halde",
      "AX_Friedhof",
      "AX_IndustrieUndGewerbeflaeche"
    ]
    osm_landuse_no_residents: ["farmyard","quarry","industrial","retail","commercial","military","cemetery","landfill","allotments","recreation ground","railway"]
    #All buildings that can be potentially residential
    building_types_potentially_residential: ["residential","yes","house","detached","terrace","apartments","home","semidetached_house"]
    #All buildings that are definitely residential
    building_types_residential: ["residential","detached","terrace","apartments","home","semidetached_house"]
    tourism_no_residents: ["zoo"]
    amenity_no_residents: ["hospital","university","community_centre","school","kindergarten","recreation_ground","wood"]
    amenity_opening_hours: ["atm","art","bakery","bank","bar","beverages","biergarten","books","butcher","cafe","chemist","clothes","coffee",
      "convenience","dentist","discount_supermarket","doctors","driving_school","fast_food","fuel","hairdresser","hookah_lounge","hypermarket","ice_cream",
      "international_supermarket","kiosk","library","museum","organic","pharmacy","post_office","pub","restaurant","social_facility","supermarket",
      "toilets","veterinary"]
    default_building_levels: '3'
    minimum_building_size_residential: '54'
    census_minimum_number_new_buildings: '1'
    average_gross_living_area: '50'
    chains_discount_supermarket: ["Aldi","Penny","Lidl","Netto","Norma"]
    chains_hypermarket: ["Hit","Real","Kaufland","V-Markt","Marktkauf"]
    chains_health_food: ["Vitalia","Reformhaus"]
    no_end_consumer_store: ["Hamberger","Metro"]
    operators_bicycle_rental: ["Münchner Verkehrs gesellschaft","Münchner Verkehrsgesellschaft","MVG"]
    wheelchair:
      smoothness_no: ["very_bad","horrible","very_horrible","impassable"]
      smoothness_limited: ['bad']
      surface_no: ['ground','grass','sand','dirt','unhewn_cobblestone','unpaved']
      surface_limited: ['gravel']
      highway_onstreet_yes: ['living_street']
      highway_onstreet_limited: ['residential','service']
    lit: 
      highway_yes: ['living_street','residential','secondary','tertiary']
      highway_no: ['track']
      surface_no: ['ground','gravel','unpaved','grass']
    walking_speed_elderly: '0.83333'
    walking_speed_wheelchair: '1.38889'
    cycling_surface:
      paving_stones: '0.2'
      sett: '0.3'
      unhewn_cobblestone: '0.3'
      cobblestone: '0.3'
      pebblestone: '0.3'
      unpaved: '0.2'
      compacted: '0.05'
      fine_gravel: '0.05'
      gravel: '0.3'
      sand: '0.4'
      grass: '0.25'
      mud: '0.4'

    cycling_smoothness:
      intermediate: '0.05'
      bad: '0.1'
      very_bad: '0.2'
      horrible: '0.3'
      very_horrible: '0.5'
    dem_resolution: '30'
    # types where employees that work all over are wrongly registered at one single point (e.g. 50000 jobs at the headquaters site)
    company_types_requiring_employment_adjustment: ["Konzernsitz", "Mehrbetriebsunternehmen"]
    # cutoff under which we don't touch the number of registered employees (the assumption is that a small number of employees doesn't work all over)
    save_employees_cutoff: '10'
    # total number of employees copanie types above and poi employees will be adjusted so that in the end the total number of employees fits this value
    total_employees: '874000'
    # number of employees for amenities
    poi_employees:
      administration: '30'
      advertising: '5'
      agrarian: '3'
      alcohol: '3'
      animal_breeding: '2'
      animal_shelter: '3'
      animal_training: '2'
      antiques: '2'
      apartment: '1'
      arts_centre: '5'
      auction_house: '5'
      baby_goods: '3'
      bag: '3'
      bakery: '3 '
      bank: '6'
      bar: '6'
      bathroom_furnishing: '4'
      beauty: '4'
      bed: '3'
      beverages: '2'
      bicycle_rental: '3'
      bicycle_repair_station: '3'
      biergarten: '7'
      boat_rental: '3'
      boat_storage: '2'
      boathouse: '2'
      bookmaker: '2'
      butcher: '3'
      cafe: '5'
      car: '6'
      caravan_site: '2'
      charity: '3'
      chemist: '4'
      childcare: '5'
      cinema: '12'
      clothes: '5'
      construction: '5'
      convenience: '6'
      dentist: '6'
      discount_supermarket: '15'
      doctors: '6'
      erotic: '2'
      fabric: '3'
      fashion: '7'
      fast_food: '6'
      florist: '3'
      fuel: '2'
      furnace: '5'
      gallery: '3'
      glaziery: '3'
      greengrocer: '5'
      guest_house: '5'
      hairdresser: '4'
      hardware: '20'
      health_food: '15'
      hostel: '5'
      hotel: '10'
      hypermarket: '30'
      ice_cream: '3'
      international_supermarket: '10'
      kindergarten: '15'
      kiosk: '1'
      library: '5'
      mall: '50'
      marketplace: '8'
      museum: '20'
      night_club: '7'
      organic: '5'
      parking: '1'
      pharmacy: '4'
      photo: '1'
      piercing: '3'
      post_office: '4'
      police: '10'
      primary_school: '25'
      pub: '6'
      research_institute: '10'
      restaurant: '7'
      secondary_school: '35'
      shoes: '5'
      sports: '5'
      studio: '3'
      supermarket: '15'
      theatre: '12'
      toys: '5'
      trade: '5'
      trailer: '2'
      tyres: '3'
      wine: '2'
      youth_centre: '6'

      
