DATABASE:
  HOST: "localhost"
  PORT: 5432
  DB_NAME: "goat"
  USER: "goat"
  PASSWORD: "earlmanigault"

DATA_SOURCE:  
  #"no_download" if you don't want to download OSM data automatically. Make sure that the file is called raw-osm.osm.pbf.
  OSM_DOWNLOAD_LINK: "https://download.geofabrik.de/europe/germany/bayern/oberbayern-latest.osm.pbf" 
  #"most_recent" if the data from the OSM-Download-Link has not the recency you need. 
  OSM_DATA_RECENCY: "standard"
  BUFFER_BOUNDING_BOX: 0.045 #in degree (default: approx. 3km)
  EXTRACT_BBOX: "yes"
  

DATA_REFINEMENT_VARIABLES:
  #extrapolation ==> census.shp + landuse.shp needed as input
  #disaggregation ==> landuse.shp needed as input + high-resolution population input data + building data
  #distribution ==> landuse.sho need as input + high-resolution population input data 
  #custom_population ==> population.shp custom population data needed  
  POPULATION: "extrapolation"
  #"yes" if you want to add these layers 
  ADDITIONAL_WALKABILITY_LAYERS: "no" 
  variable_container: 
    pois_one_entrance: ["kindergarten","primary_school","secondary_school","bar","biergarten","cafe","pub","fast_food","ice_cream","restaurant","theatre","sum_population","cinema","library","night_club","recycling",
      "car_sharing","bicycle_rental","charging_station","bus_station","tram_station","subway_station","railway_station","taxi","hairdresser","atm","bank","dentist","doctors","pharmacy","post_box","post_office","fuel",
      "bakery","butcher","clothes","convenience","general","fashion","florist","greengrocer","kiosk","mall","shoes","sports","supermarket","health_food","discount_supermarket",
      "hypermarket","international_supermarket","chemist","organic","marketplace",
      "hotel","museum","hostel","guest_house","viewpoint","gallery"
    ]
    pois_more_entrances: ["bus_stop","tram_stop","subway_entrance","rail_station"]
    excluded_class_id_walking: [0,101,102,103,104,105,106,107,501,502,503,504,701,801]
    categories_no_foot: ["use_sidepath","no"]
    excluded_class_id_cycling: [0,101,102,103,104,105,106,107,501,502,503,504,701,801]
    categories_no_bicycle: ["use_sidepath","no"]
    categories_sidewalk_no_foot: ["separate"] #Used for visualization purpose only
    max_length_links: '300'
    custom_landuse_no_residents: ["AX_TagebauGrubeSteinbruch",
      "AX_SportFreizeitUndErholungsflaeche",
      "AX_FlaecheBesondererFunktionalerPraegung",
      "AX_Halde",
      "AX_Friedhof",
      "AX_IndustrieUndGewerbeflaeche"
    ]
    osm_landuse_no_residents: ["farmyard","quarry","industrial","retail","commercial","military","cemetery","landfill","allotments","recreation ground","railway"]
    #All buildings that can be potentially residential
    building_types_potentially_residential: ["residential","yes","house","detached","terrace","apartments","home","semidetached_house"]
    #All buildings that are definitely residential
    building_types_residential: ["residential","detached","terrace","apartments","home","semidetached_house"]
    tourism_no_residents: ["zoo"]
    amenity_no_residents: ["hospital","university","community_centre","school","kindergarten","recreation_ground","wood"]
    amenity_opening_hours: ["atm","art","bakery","bank","bar","beverages","biergarten","books","butcher","cafe","chemist","clothes","coffee",
      "convenience","dentist","discount_supermarket","doctors","driving_school","fast_food","fuel","hairdresser","hookah_lounge","hypermarket","ice_cream",
      "international_supermarket","kiosk","library","museum","organic","pharmacy","post_office","pub","restaurant","social_facility","supermarket",
      "toilets","veterinary"]
    default_building_levels: '3'
    minimum_building_size_residential: '54'
    census_minimum_number_new_buildings: '1'
    average_gross_living_area: '50'
    chains_discount_supermarket: ["Aldi","Penny","Lidl","Netto","Norma"]
    chains_hypermarket: ["Hit","Real","Kaufland","V-Markt","Marktkauf"]
    chains_health_food: ["Vitalia","Reformhaus"]
    no_end_consumer_store: ["Hamberger","Metro"]
    operators_bicycle_rental: ["Münchner Verkehrs gesellschaft","Münchner Verkehrsgesellschaft","MVG"]
    wheelchair:
      smoothness_no: ["very_bad","horrible","very_horrible","impassable"]
      smoothness_limited: ['bad']
      surface_no: ['ground','grass','sand','dirt','unhewn_cobblestone','unpaved']
      surface_limited: ['gravel']
      highway_onstreet_yes: ['living_street']
      highway_onstreet_limited: ['residential','service']
    lit: 
      highway_yes: ['living_street','residential','secondary','tertiary']
      highway_no: ['track']
      surface_no: ['ground','gravel','unpaved','grass']
    walking_speed_elderly: '0.83333'
    walking_speed_wheelchair: '1.38889'
    cycling_surface:
      paving_stones: '0.2'
      sett: '0.3'
      unhewn_cobblestone: '0.3'
      cobblestone: '0.3'
      pebblestone: '0.3'
      unpaved: '0.2'
      compacted: '0.05'
      fine_gravel: '0.05'
      gravel: '0.3'
      sand: '0.4'
      grass: '0.25'
      mud: '0.4'

    cycling_smoothness:
      intermediate: '0.05'
      bad: '0.1'
      very_bad: '0.2'
      horrible: '0.3'
      very_horrible: '0.5'
    dem_resolution: '30'

      
