DATA_SOURCE:  
  #"no_download" if you don't want to download OSM data automatically. Make sure that the file is called raw-osm.osm.pbf.
  OSM_DOWNLOAD_LINK: "https://download.geofabrik.de/europe/italy/nord-ovest-latest.osm.pbf" 
  BUFFER_BOUNDING_BOX: 0.045 #in degree (default: approx. 3km)
  EXTRACT_BBOX: "yes" #"yes" ==> Use study area as BBOX,"no_extract" ==> Import whole dump, "done" ==> Extract was already done 
  
DATA_REFINEMENT_VARIABLES:
  #extrapolation ==> census.shp + landuse.shp needed as input
  #disaggregation ==> landuse.shp needed as input + high-resolution population input data + building data
  #distribution ==> landuse.sho need as input + high-resolution population input data 
  #custom_population ==> population.shp custom population data needed  
  POPULATION: "custom_population"
  #"yes" if you want to add these layers 
  ADDITIONAL_WALKABILITY_LAYERS: "yes" 
  OSM_MAPPING_FEATURE: "no"
  variable_container:
    heatmap_sensitivities: [150000,200000,250000,300000,350000,400000,450000]
    pois_one_entrance: ["kindergarten","nursery","primary_school","secondary_school","grundschule","hauptschule","realschule","werkrealschule","gymnasium","bar","biergarten","cafe","pub","fast_food","ice_cream","restaurant","theatre","sum_population","cinema","library","nightclub","recycling",
      "car_sharing","bicycle_rental","cargo_bike","charging_station","bus_station","tram_station","subway_station","railway_station","taxi","bikesharing_ffb","carsharing_ffb","charging_station_marker_ffb","charging_station_other_ffb","charging_station_public_ffb","e_parking_ffb",
      "l-station_ffb","s-station_prio1_ffb","s-station_prio2_ffb","hairdresser","atm","bank","dentist","doctors","pharmacy","post_box","post_office","fuel",
      "bakery","butcher","clothes","convenience","general","fashion","florist","greengrocer","kiosk","mall","shoes","sports","supermarket","health_food","discount_supermarket",
      "hypermarket","international_supermarket","chemist","organic","marketplace","hotel","museum","hostel","guest_house","viewpoint","gallery","playground","discount_gym","gym","yoga","outdoor_fitness_station"
    ]
    pois_more_entrances: ["bus_stop","tram_stop","subway_entrance","rail_station","community_sports_center","waterpark","park","forest","heath_scrub","lake","river"]
    excluded_class_id_walking: [0,101,102,103,104,105,106,107,501,502,503,504,701,801]
    categories_no_foot: ["use_sidepath","no"]
    excluded_class_id_cycling: [0,101,102,103,104,105,106,107,501,502,503,504,701,801]
    categories_no_bicycle: ["use_sidepath","no"]
    categories_sidewalk_no_foot: ["separate"] #Used for visualization purpose only
    max_length_links: '300'
    custom_landuse_no_residents: ["AX_TagebauGrubeSteinbruch",
      "AX_SportFreizeitUndErholungsflaeche",
      "AX_FlaecheBesondererFunktionalerPraegung",
      "AX_BauwerkOderAnlageFuerSportFreizeitUndErholung",
      "AX_Halde",
      "AX_Friedhof",
      "AX_IndustrieUndGewerbeflaeche",
      "AX_Landwirtschaft",
      "AX_Wald",
      "AX_Gehoelz",
      "AX_Heide",
      "AX_Moor",
      "AX_Insel",
      "AX_Sumpf",
      "AX_UnlandVegetationsloseFlaeche",
      "AX_Vegetationsmerkmal",
      "AX_Bahnverkehr",
      "AX_Platz",
      "AX_Strassenverkehr",
      "AX_Flugverkehr",
      "AX_Fließgewaesser",
      "AX_Hafenbecken",
      "AX_StehendesGewaesser"
    ]
    custom_landuse_with_residents_name: ["%seniorenheim%"]
    custom_landuse_additional_no_residents: [
      "Water",
      "Permanent crops (vineyards, fruit trees, olive groves)",
      "Railways and associated land",
      "Herbaceous vegetation associations (natural grassland, moors...)",
      "Forests",
      "Sports and leisure facilities",
      "Other roads and associated land",
      "Green urban areas",
      "Arable land (annual crops)",
      "Fast transit roads and associated land",
      "Industrial, commercial, public, military and private units",
      "Mineral extraction and dump sites",
      "Pastures"
    ]
    osm_landuse_no_residents: ["farmyard","construction","farmland","quarry","industrial","retail","commercial","forest","military",
    "cemetery","landfill","allotments","recreation ground","railway","parking","grass","grassland","green","garages"]
    aois_no_residents: ["forest","park","lake","river","forest","park","swimming_lake"]
    #All buildings that can be potentially residential
    building_types_potentially_residential: ["yes"]
    #All buildings that are definitely residential
    building_types_residential: ["apartments","bungalow","detached","dormitory","residential","house","terrace","home","semidetached_house"]
    tourism_no_residents: ["zoo"]
    amenity_no_residents: ["hospital","university","community_centre","school","kindergarten","recreation_ground","wood"]
    default_building_levels: '3'
    minimum_building_size_residential: '30'
    census_minimum_number_new_buildings: '1'
    average_gross_living_area: '50'
    average_building_levels: '4'
    average_roof_levels: '1'
    average_height_per_level: '3.5'
    wheelchair:
      smoothness_no: ["very_bad","horrible","very_horrible","impassable"]
      smoothness_limited: ['bad']
      surface_no: ['ground','grass','sand','dirt','unhewn_cobblestone','unpaved']
      surface_limited: ['gravel']
      highway_onstreet_yes: ['living_street']
      highway_onstreet_limited: ['residential','service']
    lit: 
      highway_yes: ['living_street','residential','secondary','tertiary']
      highway_no: ['track']
      surface_no: ['ground','gravel','unpaved','grass']
    walking_speed_elderly: '0.83333'
    #walking_speed_wheelchair: '1.38889'
    cycling_surface:
      paving_stones: '0.2'
      sett: '0.3'
      unhewn_cobblestone: '0.3'
      cobblestone: '0.3'
      pebblestone: '0.3'
      unpaved: '0.2'
      compacted: '0.05'
      fine_gravel: '0.05'
      gravel: '0.3'
      sand: '0.4'
      grass: '0.25'
      mud: '0.4'
    cycling_smoothness:
      intermediate: '0.05'
      bad: '0.1'
      very_bad: '0.2'
      horrible: '0.3'
      very_horrible: '0.5'
    cycling_crossings_delay:
      delay_1: 15
      delay_2: 30
    compute_slope_impedance: "'no'"

    #--------------------------------------
    #IAPI speed & comfort impedance factors
    categories: ['was','wac','cys','cyc','whs','whc']
    bridge_tunnel:
      bridge: ['yes','viaduct']
      tunnel: ['yes','covered']
    class_cyclepath:
      segregated_yes: ['cycleway']
    class_obstacle:
      light: ['stop','street_lamp','traffic_signal']
      moderate: ['limited','no']
      strong: ['steps']
    positive_classified:
      
    #wac = walking comfort
    walking_type_road:
      motorway: '1'
      trunk: '1'
      primary: '0.8'
      secondary: '0.6'
      tertiary : '0.2'
      unclassified: '0.2'
      residential: '0.2'
      living streets: '0'
      service: '0.05'
      pedestrain: '0'
      track: '0.1'
      footway: '0.1'
      corridor: '0'
      path: '0'
      tunnel: '0.25'
      bridge: '0.25'
    walking_peak_hour: '0.15'
    walking_cyclepath:
      segregated_yes: '0.5'
      segregated_no: '0'
    walking_sidewalk:
      ideal: '0'
      comfortable: '0'
      acceptable: '0.3'
      uncomfortable: '0.5'
    walking_obstacle:
      light: '0.05'
      moderate: '0.05'
      strong: '0.3'
    walking_surface:
      paving_stones: '0'
      sett: '0.05'
      unhewn-cobblestone: '0.05'
      cobblestone: '0.05'
      pebblestone: '0.05'
      unpaved: '0'
      compacted : '0'
      fine_gravel: '0'
      gravel: '0'
      sand: '0.1'
      grass: '0'
      mud: '0.1'
    walking_smoothness:
      intermediate: '0'
      bad: '0'
      very_bad: '0'
      horrible: '0'
      very_horrible: '0.1'
    walking_extra:
      no_park: '0.1'
      no_street_lamp: '0.2'
      no_tree: '0.2'
      no_bench: '0.1'
      no_bicycle_rack: '0'
      no_water: '0.1'

    #cyc = cycling comfort
    cycling_type_road:
      motorway: '1'
      trunk: '1'
      primary: '0.3'
      secondary: '0.2'
      tertiary : '0.1'
      unclassified: '0.1'
      residential: '0.1'
      living streets: '0'
      service: '0.05'
      pedestrain: '0.5'
      track: '0'
      footway: '0.2'
      corridor: '1'
      path: '0.1'
      tunnel: '0.25'
      bridge: '0.25'
    cycling_peak_hour: '0.075'
    cycling_cyclepath:
      segregated_yes: '0'
      segregated_no: '0.05'
    cycling_sidewalk:
      ideal: '0.05'
      comfortable: '0.1'
      acceptable: '0.2'
      uncomfortable: '0.3'
    cycling_obstacle:
      light: '0.05'
      moderate: '0.35'
      strong: '0.15'
    cycling_surface:
      paving_stones: '0.1'
      sett: '0.15'
      unhewn-cobblestone: '0.15'
      cobblestone: '0.15'
      pebblestone: '0.15'
      unpaved: '0.1'
      compacted : '0.025'
      fine_gravel: '0.025'
      gravel: '0.15'
      sand: '0.2'
      grass: '0.125'
      mud: '0.2'
    cycling_smoothness:
      intermediate: '0.025'
      bad: '0.05'
      very_bad: '0.1'
      horrible: '0.15'
      very_horrible: '0.25'
    cycling_extra:
      no_park: '0.1'
      no_street_lamp: '0.2'
      no_tree: '0.2'
      no_bench: '0.1'
      no_bicycle_rack: '0.2'
      no_water: '0'

    #whc = wheelchair comfort
    wheelchair_type_road:
      motorway: '1'
      trunk: '1'
      primary: '0.8'
      secondary: '0.7'
      tertiary : '0.3'
      unclassified: '0.3'
      residential: '0.3'
      living streets: '0'
      service: '0.05'
      pedestrain: '0'
      track: '0.1'
      footway: '0'
      corridor: '0'
      path: '0'
      tunnel: '0.25'
      bridge: '0.25'
    wheelchair_peak_hour: '0.075'
    wheelchair_cyclepath:
      segregated_yes: '0.3'
      segregated_no: '0'
    wheelchair_sidewalk:
      ideal: '0'
      comfortable: '0.1'
      acceptable: '0.2'
      uncomfortable: '0.3'
    wheelchair_obstacle:
      light: '0.05'
      moderate: '0.35'
      strong: '0.375'
    wheelchair_surface:
      paving_stones: '0.1'
      sett: '0.15'
      unhewn-cobblestone: '0.15'
      cobblestone: '0.15'
      pebblestone: '0.15'
      unpaved: '0.1'
      compacted : '0.025'
      fine_gravel: '0.025'
      gravel: '0.15'
      sand: '0.2'
      grass: '0.125'
      mud: '0.2'
    wheelchair_smoothness:
      intermediate: '0.025'
      bad: '0.05'
      very_bad: '0.1'
      horrible: '0.15'
      very_horrible: '0.25'
    wheelchair_extra:
      no_park: '0.1'
      no_street_lamp: '0.2'
      no_tree: '0.2'
      no_bench: '0.1'
      no_bicycle_rack: '0'
      no_water: '0.1'

    ##-------------------------------------Size limits for areas of interest------------------------------------##
    ## Limits the area to be displayed for certain amenities (like parks). The limits should be defined in square meters
    areas_boundaries:
      parks:
        small: [2000]
        ##large: [300000]
      forest:
        small: [2000]
        ##large: [300000]
      heath:
        small: [0]
        ##large: [300000]

    ##-------------------------------------Radius definition for POIS fusion------------------------------------##
    ##  Duplicated lookup radius: Sensibility factor, entities for the same branch and amenity type into this radius will be considered as duplicated; it is applied for OSM and Custom POIS databases (meters).
    ##  Tag new radius: Radius search for tag opening hours from Custom POIS to OSM POIS (meters).
    ##  Duplicated kindergarten lookup radius: the estimated distance between centroids of two polygons that represent the same kindergarten
    duplicated_lookup_radius: '100' 
    tag_new_radius: '130'
    duplicated_kindergarten_lookup_radius: '50'
    duplicated_primary_school_lookup_radius: '40'
    duplicated_secondary_school_lookup_radius: '40'
    one_meter_degree: '0.000009'
    ##----------------------------------------------------------------------------------------------------------##
    ##-----------Definition of amenity parameters for POIS preparation and data fusion of new sources-----------##
    ##----------------------------------------------------------------------------------------------------------##
    ##  Data structure: Amenity type -> Sub category -> Name variables or Amenity type -> Name variables
    ##  Amenity type: According to the types defined for GOAT
    ##  Sub category: Business/element generic name, this name will be implemented in the data fusion
    ##  Name variables: Array that includes the name variances to increase number of the matching POIs.
    pois_search_conditions:
      chemist:
        dm: []
        rossmann: []
      supermarket:
        edeka: ['e center', 'edeka']
        rewe: ['rewe', 'rewe city']
      discount_supermarket:
        aldi: []
        lidl: []
        penny: []
        netto: []
        norma: []
      hypermarket:
        hit: []
        real: []
        kaufland: []
        v-markt: []
        marktkauf: []
      no_end_consumer_store:
        hamberger: []
        metro: []
      health_food:
        vitalia: []
        reformhaus: []
      operators_bicycle_rental: ['münchner verkehrs gesellschaft','münchner verkehrsgesellschaft','mvg','Clear Channel','clear channel']
      bank: 
        sparkasse: ['kreissparkasse','sparkasse','stadtsparkasse']   
        hypovereinsbank: ['hypo vereinsbank', 'hypovereinsbank']
        raiffeisenbank: ['raiffeisenbank', 'vr bank', 'vr-bank', 'volksbank','volks', 'Münchner']
      fast_food:
        mcdonalds: ['mcdonald']
      restaurant:   
        vapiano: ['vapiano']
      nursery: ['krippe','kinderkrippe','kita']
      discount_gym:
        fitstar: ['fit-star','fit star']
        mcfit: []
        fitx: []
        cleverfit: ['clever fit','cleverfit']
        jumpersfitness: ['jumpers fitness']
      community_sport_centre: ['bezirkssportanlage']

    ##----------------------------------------------------------------------------------------------------------##
    ##-----------------------Amenity parameters for POIS preparation leisure and schools------------------------##
    ##----------------------------------------------------------------------------------------------------------##
    ##  Data structure:   Amenity type -> add/discard -> different parameters definition
    ##  Amenity type:     Fixed parameter, do not change it
    ##  Add/discard:      Fixed parameter, do not change it
    ##  Add:              Amenity names to include into the specific category
    ##  Discard:          Amenity names to exclude to the specific category

    amenity_config:
      leisure:
        add: ['sports_hall', 'fitness_center', 'sport_center', 'track, pitch']
        discard: ['fitness_station']
      sport:
        discard: ['table_tennis']
      primary_school:
        add: ['%grund-%', '%grund %', '%grundsch%' ]
        discard: ['%grund-schule%']
      secondary_school:
        add: ['%haupt-%', '%haupt %', '%hauptsch%', '%mittel-%', '%mittel %', '%mittelsch%', '%real-%', 'real %', '%realsch%', '%förder-%', '%förder %', '%fördersch%',
        '%gesamt-%', '%gesamt %', '%gesamtsch%', '%-gymnasium%', '%gymnasium-%', '% gymnasium%','%gymnasium %', '%fachobersch%']
        discard: ['%haupt-schule%', '%mittel-schule%', '%real-schule%', '%förder-schule%', '%gesamt-schule%']
      kindergarten: ['kindergarten']
      

    ##----------------------------------------------------------------------------------------------------------##
    ##-----------------------Definition of the weights for the Walkability index -------------------------------##
    ##----------------------------------------------------------------------------------------------------------##

    walkability:
      sidewalk_quality: 
        sidewalk_availability: 1
        sidewalk_width: 1
        pavement_quality: 1
        freedom_of_barriers: 1
        ##path_type: 0 - does it makes sense to inluce this?
      impacts_road_traffic:
        lanes: 1
        one_way: 1
        noise: 1 
        speed_limits: 2
        parking: 1
        accidents: 1 
        ##traffic_load: 0 - can we find information on this?
        ##share_heavy_load: 0 - can we find information on this?
        ##spatial_separation: 0 - can we somehow include this?
        ##number_crossings: 0 - does it makes sence to include this?
      security:
        illumination: 1
        ##social_hotspots: 0 - can we find information on this?
      green_index:
        vegetation: 1
        water: 1
      environment:
        landuse: 1
        pois: 1
        population: 1 
        ##weather_protection: 0
        ##inner_city_aeration: 0
        ##builtenvironment: 0
        ##cleanliness: 0
      comfort:
        street_furniture: 2
        slope: 2
        toilets: 1
        fountains: 1
        ##waiting_time_crossing: 0
        ##width_street_crossing
        ##marking_street_crossing
        ##orientation








      
