apiVersion: v1
kind: Namespace
metadata:
  name: ${NAMESPACE}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: ${NAMESPACE}
  labels:
    app: postgres
data:
  POSTGRES_DBNAME: ${POSTGRES_DB}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASS: ${POSTGRES_PASSWORD}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  namespace: ${NAMESPACE}
  labels:
    app: postgres
spec:
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: ${NAMESPACE}
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: ${POSTGIS_DOCKER_IMAGE}
          imagePullPolicy: "IfNotPresent"
          # lifecycle:
          #   postStart:
          #     exec:
          #       command: ["/bin/sh", "-c", "python3", "/opt/setup_goat.py", "-t", "new_setup"]
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
            - mountPath: /opt/config/
              name: goat-config
            - mountPath: /opt/data
              name: postgredb
              subPath: ${NAMESPACE}
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
        - name: goat-config
          configMap:
            name: goat-config
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: ${NAMESPACE}
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
   - port: 5432
  selector:
   app: postgres
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: goat-config
  namespace: ${NAMESPACE}
data:
  goat_config.yaml: |
    DATABASE:
      HOST: \"postgres.${NAMESPACE}.svc.cluster.local\"
      PORT: 5432
      DB_NAME: \"${POSTGRES_DB}\"
      USER: \"${POSTGRES_USER}\"
      PASSWORD: \"${POSTGRES_PASSWORD}\"

    DATA_SOURCE:
      OSM_DOWNLOAD_LINK: \"no_download\" #\"https://download.geofabrik.de/europe/germany/bayern/oberbayern-latest.osm.pbf\"
      OSM_DATA_RECENCY: \"standard\"
      BUFFER_BOUNDING_BOX: 0.045 #in degree (default: approx. 3km)

    DATA_SOURCE:  
      #\"no_download\" if you don't want to download OSM data automatically. Make sure that the file is called raw-osm.osm.pbf.
      OSM_DOWNLOAD_LINK: \"https://download.geofabrik.de/europe/germany/bayern/oberbayern-latest.osm.pbf\" 
      #\"most_recent\" if the data from the OSM-Download-Link has not the recency you need. 
      OSM_DATA_RECENCY: \"standard\"
      BUFFER_BOUNDING_BOX: 0.045 #in degree (default: approx. 3km)
      

    DATA_REFINEMENT_VARIABLES:
      #extrapolation ==> census.shp + landuse.shp needed as input
      #disaggregation ==> landuse.shp needed as input + high-resolution population input data + high completness number of floors
      #custom_population ==> population.shp custom population data needed  
    
      POPULATION: \"extrapolation\"
      #\"yes\" if you want to add these layers 
      ADDITIONAL_WALKABILITY_LAYERS: \"no\" 
      variable_container: 
        poi_categories: [\"nursery\",\"kindergarten\",\"primary_school\",\"secondary_school\",\"bar\",\"biergarten\",\"cafe\",\"pub\",\"fast_food\",\"ice_cream\",\"restaurant\",\"theatre\",\"sum_population\",\"cinema\",\"library\",\"night_club\",\"recycling\",
          \"car_sharing\",\"bicycle_rental\",\"charging_station\",\"bus_station\",\"tram_station\",\"subway_station\",\"railway_station\",\"taxi\",\"hairdresser\",\"atm\",\"bank\",\"dentist\",\"doctors\",\"pharmacy\",\"post_box\",\"post_office\",\"fuel\",
          \"bakery\",\"butcher\",\"clothes\",\"convenience\",\"general\",\"fashion\",\"florist\",\"greengrocer\",\"kiosk\",\"mall\",\"shoes\",\"sports\",\"supermarket\",\"health_food\",\"discount_supermarket\",
          \"hypermarket\",\"international_supermarket\",\"chemist\",\"organic\",\"marketplace\",
          \"hotel\",\"museum\",\"hostel\",\"guest_house\",\"playground\",\"viewpoint\",\"gallery\",\"bus_stop\",
          \"tram_stop\",\"subway_entrance\",\"rail_station\"
        ]
        excluded_class_id_walking: [0,101,102,103,104,105,106,107,501,502,503,504,701,801]
        categories_no_foot: [\"use_sidepath\",\"no\"]
        excluded_class_id_cycling: [0,101,102,103,104,105,106,107,501,502,503,504,701,801]
        categories_no_bicycle: [\"use_sidepath\",\"no\"]
        categories_sidewalk_no_foot: [\"separate\"] #Used for visualization purpose only
        max_length_links: \"300\"
        custom_landuse_no_residents: [\"AX_TagebauGrubeSteinbruch\",
          \"AX_SportFreizeitUndErholungsflaeche\",
          \"AX_FlaecheBesondererFunktionalerPraegung\",
          \"AX_Halde\",
          \"AX_Friedhof\",
          \"AX_IndustrieUndGewerbeflaeche\"
        ]
        osm_landuse_no_residents: [\"farmyard\",\"quarry\",\"industrial\",\"retail\",\"commercial\",\"military\",\"cemetery\",\"landfill\",\"allotments\",\"recreation ground\",\"railway\"]
        #All buildings that can be potentially residential
        building_types_potentially_residential: [\"residential\",\"yes\",\"house\",\"detached\",\"terrace\",\"apartments\",\"home\"]
        #All buildings that are definitely residential
        building_types_residential: [\"residential\",\"detached\",\"terrace\",\"apartments\",\"home\"]
        tourism_no_residents: [\"zoo\"]
        amenity_no_residents: [\"hospital\",\"university\",\"community_centre\",\"school\",\"kindergarten\",\"recreation_ground\",\"wood\"]
        amenity_opening_hours: [\"atm\",\"art\",\"bakery\",\"bank\",\"bar\",\"beverages\",\"biergarten\",\"books\",\"butcher\",\"cafe\",\"chemist\",\"clothes\",\"coffee\",
          \"convenience\",\"dentist\",\"discount_supermarket\",\"doctors\",\"driving_school\",\"fast_food\",\"fuel\",\"hairdresser\",\"hookah_lounge\",\"hypermarket\",\"ice_cream\",
          \"international_supermarket\",\"kiosk\",\"library\",\"museum\",\"organic\",\"pharmacy\",\"post_office\",\"pub\",\"restaurant\",\"social_facility\",\"supermarket\",
          \"toilets\",\"veterinary\"]
        default_building_levels: \"3\"
        minimum_building_size_residential: \"54\"
        census_minimum_number_new_buildings: \"1\"
        average_gross_living_area: \"50\"
        chains_discount_supermarket: [\"Aldi\",\"Penny\",\"Lidl\",\"Netto\",\"Norma\"]
        chains_hypermarket: [\"Hit\",\"Real\",\"Kaufland\",\"V-Markt\",\"Marktkauf\"]
        chains_health_food: [\"Vitalia\",\"Reformhaus\"]
        no_end_consumer_store: [\"Hamberger\",\"Metro\"]
        operators_bicycle_rental: [\"Münchner Verkehrs gesellschaft\",\"Münchner Verkehrsgesellschaft\",\"MVG\"]
        wheelchair:
          smoothness_no: [\"very_bad\",\"horrible\",\"very_horrible\",\"impassable\"]
          smoothness_limited: [\"bad\"]
          surface_no: [\"ground\",\"grass\",\"sand\",\"dirt\",\"unhewn_cobblestone\",\"unpaved\"]
          surface_limited: [\"gravel\"]
          highway_onstreet_yes: [\"living_street\"]
          highway_onstreet_limited: [\"residential\",\"service\"]
        lit: 
          highway_yes: [\"living_street\",\"residential\",\"secondary\",\"tertiary\"]
          highway_no: [\"track\"]
          surface_no: [\"ground\",\"gravel\",\"unpaved\",\"grass\"]
        walking_speed_elderly: \"0.83333\"
        walking_speed_wheelchair: \"1.38889\"
