name: "Api - Release"

on:
  workflow_call:
  workflow_dispatch:


defaults:
  run:
    working-directory: app/api

jobs:

  checks:
    name: checks
    uses: ./.github/workflows/checks.yml

  release-api:
    name: release-api
    needs: checks
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Checkout
        uses: actions/checkout@v4
      
      - name: ğŸ³ Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: ğŸ³ Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: ğŸ³ Build changed api
        uses: docker/build-push-action@v4
        with:
          context: ${{ github.workspace }}/app/api
          file: ${{ github.workspace }}/app/api/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64
          tags: | 
            goatcommunity/api:${{ needs.checks.outputs.sha_short }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      