name: "Client - Next.js bundle analysis"

on:
  workflow_call:
  push:
    branches:
      - v2

defaults:
  run:
    working-directory: app/client
      
jobs:
  build:
    if: ${{ github.event_name == 'push' }}
    uses: ./.github/workflows/client-production-build.yml
    secrets: inherit
  analyze:
    needs: build
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Checkout
        uses: actions/checkout@v3

      - name: ğŸ“¥ Checkout PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: ./.github/actions/pr-git-checkout

      - name: ğŸ“¥ Monorepo install
        uses: ./.github/actions/pnpm-install
        with:
          enable-corepack: true
          cwd: ${{ github.workspace }}/app/client

      - name: ğŸ—ï¸ Build client
        uses: ./.github/actions/client-cache-build
        with:
          cwd: ${{ github.workspace }}/app/client
          
      - name: ğŸ“Š Analyze bundle 
        run: |
          cd apps/goat
          npx -p nextjs-bundle-analysis@0.5.0 report

      - name: ğŸ“¤ Upload bundle
        uses: actions/upload-artifact@v3
        with:
          name: bundle
          path: ${{ github.workspace }}/app/client/apps/goat/.next/analyze/__bundle_analysis.json

      - name: ğŸ“¥ Download base branch bundle stats
        uses: dawidd6/action-download-artifact@v2
        if: success() && github.event.number
        with:
          workflow: client-nextjs-bundle-analysis.yml
          branch: ${{ github.event.pull_request.base.ref }}
          path: ${{ github.workspace }}/app/client/apps/goat/.next/analyze/base

      # And here's the second place - this runs after we have both the current and
      # base branch bundle stats, and will compare them to determine what changed.
      # There are two configurable arguments that come from package.json:
      #
      # - budget: optional, set a budget (bytes) against which size changes are measured
      #           it's set to 350kb here by default, as informed by the following piece:
      #           https://infrequently.org/2021/03/the-performance-inequality-gap/
      #
      # - red-status-percentage: sets the percent size increase where you get a red
      #                          status indicator, defaults to 20%
      #
      # Either of these arguments can be changed or removed by editing the `nextBundleAnalysis`
      # entry in your package.json file.
      - name: ğŸ”„ Compare with base branch bundle
        if: success() && github.event.number
        run: |
          cd apps/goat
          ls -laR .next/analyze/base && npx -p nextjs-bundle-analysis compare

      - name: ğŸ’¬ Get comment body
        id: get-comment-body
        if: success() && github.event.number
        run: |
          cd apps/goat
          body=$(cat .next/analyze/__bundle_analysis_comment.txt)
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}"
          echo ::set-output name=body::$body

      - name: ğŸ’¬ Find Comment
        uses: peter-evans/find-comment@v1
        if: success() && github.event.number
        id: fc
        with:
          issue-number: ${{ github.event.number }}
          body-includes: "<!-- __NEXTJS_BUNDLE_@p4b/goat -->"

      - name: ğŸ’¬ Create Comment
        uses: peter-evans/create-or-update-comment@v1.4.4
        if: success() && github.event.number && steps.fc.outputs.comment-id == 0
        with:
          issue-number: ${{ github.event.number }}
          body: ${{ steps.get-comment-body.outputs.body }}

      - name: ğŸ’¬ Update Comment
        uses: peter-evans/create-or-update-comment@v1.4.4
        if: success() && github.event.number && steps.fc.outputs.comment-id != 0
        with:
          issue-number: ${{ github.event.number }}
          body: ${{ steps.get-comment-body.outputs.body }}
          comment-id: ${{ steps.fc.outputs.comment-id }}
          edit-mode: replace