name: "Client - Deploy"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  checks:
    name: environment
    uses: ./.github/workflows/checks.yml
    secrets: inherit

  deploy-goat:
    name: deploy-goat
    runs-on: ubuntu-latest
    needs: [checks]
    environment:
      name: ${{ needs.checks.outputs.env_name }}
    if: ${{ needs.checks.outputs.client-goat-changed == 'true' }}
    timeout-minutes : 5
    steps:
      - name: ðŸ“¥ Checkout
        uses: actions/checkout@v3

      - name: ðŸŽ¡ Setup Kubectl
        uses: azure/setup-kubectl@v3

      - name: ðŸŽ¡ Setup k8s context to home folder from base64 secret
        run: |
          mkdir -p ~/.kube
          echo ${{ secrets.KUBE_CONFIG }} | base64 -d > ~/.kube/config
          export KUBECONFIG=~/.kube/config
          
      - name: ðŸŽ¡ Test kubectl
        run: |
          kubectl get pods

      - name: ðŸš€ Deploy to k8s
        uses: azure/k8s-deploy@v4
        with:
          namespace: ${{ needs.checks.outputs.env_name }}
          action: deploy
          strategy: basic
          manifests: |
           ${{ github.workspace }}/infra/manifests/${{ needs.checks.outputs.env_name }}/client.yml
          images: |
            goatcommunity/client:feature-add-map-page