name: Client - Check Types
on:
  workflow_call:

env:
  NODE_OPTIONS: "--max-old-space-size=8192"

defaults:
  run:
    working-directory: ./app/client

jobs:
  check-types:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Checkout
        uses: actions/checkout@v3

      - name: ğŸ“¥ Checkout PR
        uses: ./.github/actions/pr-git-checkout

      - name: ğŸ“¥ Monorepo install
        uses: ./.github/actions/pnpm-install
        with:
          enable-corepack: true
          cwd: ${{ github.workspace }}/app/client

      - name: ğŸ“Š Show Info
        run: node -e "console.log(require('v8').getHeapStatistics())"

      - name: ğŸ•µï¸ Typecheck
        run: pnpm run typecheck
