name: "Client - Lint"

on:
  workflow_call:

defaults:
  run:
    working-directory: app/client

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ“¥ Checkout
        uses: actions/checkout@v4
        
      - name: ðŸ“¥ Checkout PR
        uses: ./.github/actions/pr-git-checkout

      - name: ðŸ“¥ Monorepo install
        uses: ./.github/actions/pnpm-install
        with:
          enable-corepack: true
          cwd: ${{ github.workspace }}/app/client

      - name: ðŸ”¬ Run Linting with Reports
        run: pnpm run lint:report
        continue-on-error: true

      - name: ðŸ”¬ Merge lint reports
        run: jq -s '[.[]]|flatten' lint-results/*.json &> lint-results/eslint_report.json

      - name: ðŸ”¬ Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          report-json: ${{ github.workspace }}/app/client/lint-results/eslint_report.json
          only-pr-files: false

      - name: ðŸ”¬ Upload ESLint report
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: lint-results
          path: ${{ github.workspace }}/app/client/lint-results
