name: "Docs - Release"

on:
  workflow_call:
  workflow_dispatch:


defaults:
  run:
    working-directory: docs

jobs:

  checks:
    name: checks
    uses: ./.github/workflows/checks.yml

  release-docs:
    name: release-docs
    needs: checks
    if: ${{ needs.checks.outputs.docs-changed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Checkout
        uses: actions/checkout@v3
      
      - name: ğŸ³ Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: ğŸ³ Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: ğŸ³ Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: goatcommunity/docs

      - name: ğŸ³ Build changed docs
        uses: docker/build-push-action@v4
        with:
          context: ${{ github.workspace }}/docs
          file: ${{ github.workspace }}/docs/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
    
      - name: ğŸ³ Image digest
        run: echo ${{ steps.meta.outputs.digest }}
      