name: "Lint"
on:
  workflow_call:
    inputs:
      lint-web:
        type: boolean
        description: "Whether to run web linting"
        required: false
        default: true

      lint-python:
        type: boolean
        description: "Whether to run python linting"
        required: false
        default: true

jobs:
  lint-web:
    runs-on: ubuntu-latest
    if: ${{ inputs.lint-web }}
    steps:
      - name: ðŸ“¥ Checkout
        uses: actions/checkout@v4

      - name: ðŸ“¥ Checkout PR
        uses: goat-community/.github/.github/actions/pr-git-checkout@main

      - name: ðŸ“¥ Monorepo install
        uses: goat-community/.github/.github/actions/pnpm-install@main
        with:
          enable-corepack: true
          cwd: ${{ github.workspace }}

      - name: ðŸ”¬ Run Linting with Reports
        run: pnpm run lint:report
        continue-on-error: true

      - name: ðŸ”¬ Merge lint reports
        run: jq -s '[.[]]|flatten' lint-results/*.json &> lint-results/eslint_report.json

      - name: ðŸ”¬ Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          report-json: ${{ github.workspace }}/lint-results/eslint_report.json
          only-pr-files: false

      - name: ðŸ”¬ Upload ESLint report
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: lint-results
          path: ${{ github.workspace }}/lint-results
