name: "Lint"
on:
  workflow_call:
    inputs:
      web:
        type: boolean
        description: "Whether to run web linting"
        required: false
        default: true

      python:
        type: boolean
        description: "Whether to run python linting"
        required: false
        default: true

env:
  NODE_OPTIONS: "--max-old-space-size=8192"


jobs:
  web:
    runs-on: ubuntu-latest
    if: ${{ inputs.web }}
    steps:
      - name: ğŸ“¥ Checkout
        uses: actions/checkout@v4

      - name: ğŸ“¥ Checkout PR
        uses: goat-community/.github/.github/actions/pr-git-checkout@main

      - name: ğŸ“¥ Monorepo install
        uses: goat-community/.github/.github/actions/pnpm-install@main
        with:
          enable-corepack: true
          cwd: ${{ github.workspace }}

      - name: ğŸ“Š Show Info
        run: node -e "console.log(require('v8').getHeapStatistics())"

      - name: ğŸ•µï¸ Typecheck
        run: pnpm run typecheck

      - name: ğŸ”¬ Run Linting with Reports
        run: pnpm run lint:report
        continue-on-error: true

      - name: ğŸ”¬ Merge lint reports
        run: jq -s '[.[]]|flatten' lint-results/*.json &> lint-results/eslint_report.json

      - name: ğŸ”¬ Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          report-json: ${{ github.workspace }}/lint-results/eslint_report.json
          only-pr-files: false

      - name: ğŸ”¬ Upload ESLint report
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: lint-results
          path: ${{ github.workspace }}/lint-results

  python:
    runs-on: ubuntu-latest
    if: ${{ inputs.python }}
    steps:
      - name: ğŸ“¥ Checkout
        uses: actions/checkout@v4

      - name: ğŸ“¥ Checkout PR
        uses: goat-community/.github/.github/actions/pr-git-checkout@main

      - name: ğŸ Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: ğŸ Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.5.1"
          enable-cache: true

      - name: ğŸ”¬ Run linting
        run: uv run bash scripts/lint-python.sh
        working-directory: ${{ github.workspace }}
