name: "Check Types"
on:
  workflow_call:
    inputs:
      lint-web:
        type: boolean
        description: "Whether to run web linting"
        required: false
        default: true

      lint-python:
        type: boolean
        description: "Whether to run python linting"
        required: false
        default: true

env:
  NODE_OPTIONS: "--max-old-space-size=8192"

jobs:
  typecheck:
    if: ${{ inputs.lint-web }}
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Checkout
        uses: actions/checkout@v4

      - name: ğŸ“¥ Checkout PR
        uses: goat-community/.github/.github/actions/pr-git-checkout@main

      - name: ğŸ“¥ Monorepo install
        uses: goat-community/.github/.github/actions/pnpm-install@main
        with:
          enable-corepack: true
          cwd: ${{ github.workspace }}

      - name: ğŸ“Š Show Info
        run: node -e "console.log(require('v8').getHeapStatistics())"

      - name: ğŸ•µï¸ Typecheck
        run: pnpm run typecheck
