name: "Check Types"
on:
  workflow_call:
    inputs:
      type:
        type: choice
        description: "Type of typecheck to run"
        required: false
        options:
          - "web"
          - "python"


env:
  NODE_OPTIONS: "--max-old-space-size=8192"

jobs:
  typecheck:
    if: ${{ !inputs.type || inputs.type == 'web' }}
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Checkout
        uses: actions/checkout@v4

      - name: ğŸ“¥ Checkout PR
        uses: goat-community/.github/.github/actions/pr-git-checkout@main

      - name: ğŸ“¥ Monorepo install
        uses: goat-community/.github/.github/actions/pnpm-install@main
        with:
          enable-corepack: true
          cwd: ${{ github.workspace }}

      - name: ğŸ“Š Show Info
        run: node -e "console.log(require('v8').getHeapStatistics())"

      - name: ğŸ•µï¸ Typecheck
        run: pnpm run typecheck
